version: "3"
services:
  frontend:
    container_name: blackjack_client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: blackjack/blackjack_client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
  backend:
    container_name: blackjack_server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: blackjack/blackjack_server
    ports:
      - "5051:5000"
    volumes:
      - ./server:/usr/src/app